#!/bin/bash

starttime=$(date +%s);
export HOSTNAME=$HOSTNAME:
export nthreads=8;
export datadir="$HOME/pulsegendata/h5files/";
mkdir -p $datadir;

export fsWindow=100;

export npulses=1024;

export delays_mean=0;
export delays_std=25;

export amp_mean=1;
export amp_std=1;

export lambda_0=600; #in nm
export lambda_width=200;
export lambda_onoff=10;
export tspan=10000; ##32768; ## really using this one

export noisescale=.005;

export sampleinterval=4;

export nu_low=0.492; # 610nm 
export nu_high=0.769; # 390nm 

touch logfile
# call to main #
export chirp=100; 
export TOD=10;
export FOD=1;
export fifthOD=.1;
# noise values to simulate unstable continuum, should be positive
export chirpnoise=0; 
export TODnoise=0;
export FODnoise=0;
export fifthODnoise=0;

export gain=200000000000; #20000000;
export saturate=40960;
export lamsamples=1024;


export filebase=$datadir"dataset";
echo "---	Environment variables exported";
echo "---	filebase = $filebase";
echo "---	nthreads = $nthreads";
echo "---	npulses = $npulses";

#./generate_dataset 
