#!/bin/bash

starttime=$(date +%s);
export HOSTNAME=$HOSTNAME:
export nthreads=8;
export npulses=128;
export datadir="$HOME/pulsegendata/h5files/";
mkdir -p $datadir;

export fsWindow=1000;


export delays_mean=0;
export delays_std=.001;

export amp_mean=1;
export amp_std=1;

export lambda_0=800; #in nm
export lambda_width=400;
export lambda_onoff=200; ## this should be 1/2 the width of the lambda_width to get something like a gaussian
export tspan=1000; ##32768; ## really using this one

export noisescale=.005;

export sampleinterval=4;

export nu_low=0.492; # 610nm 
export nu_high=0.769; # 390nm 

touch logfile

export amp0th=1.0
export amp1st=0.001
export amp2nd=0.001
export amp3rd=0.001
export amp4th=0.001
export amp5th=0.001

export chirp=0.025; 
export TOD=0.001;
export FOD=0.001;
export fifthOD=0.001;
# noise values to simulate unstable continuum, should be positive
export chirpnoise=0; 
export TODnoise=0;
export FODnoise=0;
export fifthODnoise=0;

export gain=1;
#export gain=200000000000; #20000000;
export saturate=40960;
export lamsamples=1024;


export filebase=$datadir"dataset";
echo "---	Environment variables exported";
echo "---	filebase = $filebase";
echo "---	nthreads = $nthreads";
echo "---	npulses = $npulses";

#./generate_dataset 
