#!/bin/bash

starttime=$(date +%s);
export HOSTNAME=$HOSTNAME:
export nthreads=8;
export npulses=128;
export datadir="$HOME/pulsegendata/h5files/";
mkdir -p $datadir;

export fsWindow=1000;


export delays_mean=0;
export delays_std=200.0;

export amp_mean=1;
export amp_std=1;

export lambda_0=800; #in nm
export lambda_width=400;
export lambda_onoff=200; ## this should be 1/2 the width of the lambda_width to get something like a gaussian
export tspan=1000; ##32768; ## really using this one

export noisescale=.005;

export sampleinterval=4;

export nu_low=0.492; # 610nm 
export nu_high=0.769; # 390nm 

touch logfile

# ensure all these amplitude modulations are in the very close vicinity of 1
#500.; # for tspan 1000 and fsPau()=.024, this gives a factor of 272034 with sqrt(272034)=522 to bring the chirp into the range of "1" for 
#let's try instead applying chirp polynomial as an exponent... then amplitude will always be positive definate
export amp0th=1.0 # I guess this one sort of causes double pulses if it's not high enough and the others cause zero crossings in the amplitude
export amp1st=2.0 # 
export amp2nd=4.0 # 
export amp3rd=8.0 # 
export amp4th=16.0 #
export amp5th=32.0 #

#500.; # for tspan 1000 and fsPau()=.024, this gives a factor of 272034 with sqrt(272034)=522 to bring the chirp into the range of "1" for 
export chirp=100.0; 
export TOD=100.0;
export FOD=100.0;
export fifthOD=100.0;
# noise values to simulate unstable continuum, should be positive
export chirpnoise=0; 
export TODnoise=0;
export FODnoise=0;
export fifthODnoise=0;

export gain=1;
#export gain=200000000000; #20000000;
export saturate=40960;
export lamsamples=1024;


export filebase=$datadir"dataset";
echo "---	Environment variables exported";
echo "---	filebase = $filebase";
echo "---	nthreads = $nthreads";
echo "---	npulses = $npulses";

#./generate_dataset 
